name: Conan Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Release, Debug]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Conan
        run: pip install conan meson ninja

      - name: Configure Conan profile
        run: |
          conan profile new default --detect || true
          conan profile update settings.compiler.libcxx=libstdc++11 default || true

      - name: Create and build package
        run: |
          conan create . --name=pizza_test --version=1.2.7 fossillogic/stable \
            -s build_type=${{ matrix.build_type }}

      - name: Run test package
        run: |
          mkdir test_package_build && cd test_package_build
          conan install ../test_package --build=missing
          conan build ../test_package