name: Archive CD

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.2.3

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04  # Base container for building

    env:
      PROJECT_NAME: fossil-test
      BUILD_DIR: builddir
      DIST_DIR: dist
      GHCR_IMAGE: ghcr.io/${{ github.repository_owner }}/fossil-test:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt update
          apt install -y python3 python3-pip meson ninja-build build-essential curl docker.io git
          pip3 install --upgrade pip

      - name: Set up Meson build
        run: |
          meson setup $BUILD_DIR

      - name: Compile project
        run: meson compile -C $BUILD_DIR

      - name: Generate source archives
        run: |
          meson dist -C $BUILD_DIR --formats xztar,bztar,gztar,zip
          mkdir -p $DIST_DIR
          cp $BUILD_DIR/meson-dist/* $DIST_DIR/

      - name: List archives
        run: ls -l $DIST_DIR

      - name: Build Docker image
        run: |
          # Dockerfile should be in repo root
          docker build -t $GHCR_IMAGE .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push $GHCR_IMAGE

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: source-archives
          path: $DIST_DIR/
